"""
Train UNet for SAR Oil Spill Segmentation
==========================================
Uses VanillaUNet with SARPreprocessor (versioned preprocessing).

IMPORTANT NOTICE
----------------
This training script currently uses SYNTHETIC SAR data generated by
SyntheticSARDataset. Results are NOT real-world Sentinel-1 metrics.

To train on real data:
  1. Set REAL_DATA_DIR to a directory containing:
       images/  — paired (VV, VH) GeoTIFF files
       masks/   — binary segmentation masks (0=background, 1=spill)
  2. Set USE_REAL_DATA=True below.

See docs/real_data_format.md for the expected dataset structure.
"""

from __future__ import annotations
import os
import sys
import json
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader, random_split

BASE_DIR    = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(BASE_DIR)
MODELS_DIR  = os.path.join(PROJECT_DIR, "models")
sys.path.insert(0, PROJECT_DIR)

from sar_pipeline.unet_model import VanillaUNet, save_checkpoint
from sar_pipeline.sar_preprocessor import SARPreprocessor, PREPROCESSING_VERSION

# ─── Configuration ────────────────────────────────────────────
EPOCHS          = int(os.environ.get("TRAIN_EPOCHS", 30))
BATCH_SIZE      = int(os.environ.get("TRAIN_BATCH", 8))
LEARNING_RATE   = float(os.environ.get("TRAIN_LR", 1e-3))
N_SYNTHETIC     = int(os.environ.get("TRAIN_N_SYNTHETIC", 800))
USE_REAL_DATA   = os.environ.get("USE_REAL_DATA", "false").lower() == "true"
REAL_DATA_DIR   = os.environ.get("REAL_DATA_DIR", "")
DEVICE          = "cuda" if torch.cuda.is_available() else "cpu"
MODEL_OUT       = os.path.join(MODELS_DIR, "sar_unet_oil_spill.pt")
METRICS_OUT     = os.path.join(MODELS_DIR, "sar_unet_metrics.json")
# ──────────────────────────────────────────────────────────────


# ─── Shared preprocessor instance ─────────────────────────────
preprocessor = SARPreprocessor()
# ──────────────────────────────────────────────────────────────


class SyntheticSARDataset(Dataset):
    """
    Synthetic Sentinel-1-like SAR dataset for prototype training.

    SYNTHETIC DATA — NOT real Sentinel-1 imagery.
    Generates simple geometric oil-spill patterns with realistic
    backscatter statistics for unit testing and initial prototyping.
    """

    def __init__(self, n_samples: int = 800, image_size: int = 512, seed: int = 42):
        self.n_samples  = n_samples
        self.image_size = image_size
        self.rng        = np.random.RandomState(seed)
        self._label     = "[SYNTHETIC]"  # always present in data source label

    def __len__(self) -> int:
        return self.n_samples

    def __getitem__(self, idx: int):
        size = self.image_size
        rng  = self.rng

        # Background: Gaussian noise simulating ocean VV/VH linear backscatter
        # VV ~0.01–0.25 (linear), VH ~0.001–0.04 (linear)
        vv_bg = np.abs(rng.normal(0.06, 0.02, (size, size))).astype(np.float32)
        vh_bg = np.abs(rng.normal(0.01, 0.004, (size, size))).astype(np.float32)

        mask = np.zeros((size, size), dtype=np.float32)

        # ~50% chance of spill present
        if rng.rand() > 0.5:
            # Elliptical spill region with reduced backscatter
            cy   = rng.randint(size // 4, 3 * size // 4)
            cx   = rng.randint(size // 4, 3 * size // 4)
            ry   = rng.randint(20, 100)
            rx   = rng.randint(40, 200)
            angle = rng.uniform(0, np.pi)

            Y, X = np.mgrid[:size, :size]
            cos_a = np.cos(angle)
            sin_a = np.sin(angle)
            Xr = cos_a * (X - cx) + sin_a * (Y - cy)
            Yr = -sin_a * (X - cx) + cos_a * (Y - cy)
            region = ((Xr / rx) ** 2 + (Yr / ry) ** 2) <= 1

            # Oil damping: reduce backscatter in spill region
            damping_vv = rng.uniform(0.3, 0.6)
            damping_vh = rng.uniform(0.25, 0.55)
            vv_bg[region] *= damping_vv
            vh_bg[region] *= damping_vh

            # Clip to physical range
            vv_bg = np.clip(vv_bg, 1e-10, 1.0)
            vh_bg = np.clip(vh_bg, 1e-10, 1.0)

            mask[region] = 1.0

        # Use the shared preprocessor (same as inference)
        tensor = preprocessor.preprocess_pair(vv_bg, vh_bg)  # (2, H, W)
        img    = torch.from_numpy(tensor)
        gt     = torch.from_numpy(mask).unsqueeze(0)          # (1, H, W)

        return img, gt


def dice_loss(pred: torch.Tensor, target: torch.Tensor, smooth: float = 1.0) -> torch.Tensor:
    pred_f   = torch.sigmoid(pred).view(-1)
    target_f = target.view(-1)
    inter    = (pred_f * target_f).sum()
    return 1.0 - (2.0 * inter + smooth) / (pred_f.sum() + target_f.sum() + smooth)


def combined_loss(pred: torch.Tensor, target: torch.Tensor) -> torch.Tensor:
    bce  = nn.functional.binary_cross_entropy_with_logits(pred, target)
    dice = dice_loss(pred, target)
    return 0.5 * bce + 0.5 * dice


def compute_metrics(pred_prob: np.ndarray, target: np.ndarray, threshold: float = 0.5) -> dict:
    pred_bin = (pred_prob >= threshold).astype(float)
    tp = float(((pred_bin == 1) & (target == 1)).sum())
    fp = float(((pred_bin == 1) & (target == 0)).sum())
    fn = float(((pred_bin == 0) & (target == 1)).sum())
    tn = float(((pred_bin == 0) & (target == 0)).sum())

    precision = tp / max(tp + fp, 1e-6)
    recall    = tp / max(tp + fn, 1e-6)
    iou       = tp / max(tp + fp + fn, 1e-6)
    dice      = 2 * tp / max(2 * tp + fp + fn, 1e-6)
    f1        = dice
    return dict(precision=precision, recall=recall, iou=iou, dice=dice, f1=f1)


def train():
    os.makedirs(MODELS_DIR, exist_ok=True)
    print("=" * 65)
    print("SAR U-Net Oil Spill Segmentation — Training")
    print("=" * 65)
    print(f"  Architecture   : VanillaUNet")
    print(f"  Input channels : 2 (VV, VH)")
    print(f"  Image size     : 512 x 512")
    print(f"  Preprocessing  : {PREPROCESSING_VERSION}")
    print(f"  Device         : {DEVICE}")
    print(f"  Epochs         : {EPOCHS}")
    print(f"  Batch size     : {BATCH_SIZE}")
    print(f"  Dataset        : {'REAL + SYNTHETIC' if USE_REAL_DATA else 'SYNTHETIC ONLY'}")
    print()

    # Build dataset
    dataset = SyntheticSARDataset(n_samples=N_SYNTHETIC)
    # TODO: if USE_REAL_DATA and REAL_DATA_DIR: merge with RealSARDataset(REAL_DATA_DIR)

    n_val   = max(1, int(len(dataset) * 0.15))
    n_train = len(dataset) - n_val
    train_ds, val_ds = random_split(dataset, [n_train, n_val],
                                    generator=torch.Generator().manual_seed(42))

    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True,  num_workers=0)
    val_loader   = DataLoader(val_ds,   batch_size=BATCH_SIZE, shuffle=False, num_workers=0)

    print(f"  Train samples  : {n_train}")
    print(f"  Val samples    : {n_val}")
    print()

    model     = VanillaUNet(in_channels=2, base_features=32).to(DEVICE)
    optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)
    scheduler = optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode="min",
                                                     factor=0.5, patience=5)

    best_val_loss = float("inf")
    best_epoch    = 0
    history       = []

    for epoch in range(1, EPOCHS + 1):
        # ── Train ──
        model.train()
        train_loss = 0.0
        for imgs, masks in train_loader:
            imgs, masks = imgs.to(DEVICE), masks.to(DEVICE)
            optimizer.zero_grad()
            preds = model(imgs)
            loss  = combined_loss(preds, masks)
            loss.backward()
            optimizer.step()
            train_loss += loss.item()
        train_loss /= len(train_loader)

        # ── Validate ──
        model.eval()
        val_loss      = 0.0
        all_probs     = []
        all_targets   = []
        with torch.no_grad():
            for imgs, masks in val_loader:
                imgs, masks = imgs.to(DEVICE), masks.to(DEVICE)
                preds   = model(imgs)
                loss    = combined_loss(preds, masks)
                val_loss += loss.item()
                probs   = torch.sigmoid(preds).cpu().numpy()
                all_probs.append(probs)
                all_targets.append(masks.cpu().numpy())
        val_loss /= len(val_loader)
        scheduler.step(val_loss)

        metrics = compute_metrics(
            np.concatenate(all_probs).flatten(),
            np.concatenate(all_targets).flatten()
        )

        history.append({"epoch": epoch, "train_loss": round(train_loss, 4),
                         "val_loss": round(val_loss, 4), **{k: round(v, 4) for k, v in metrics.items()}})

        print(f"Epoch {epoch:3d}/{EPOCHS}  "
              f"train={train_loss:.4f}  val={val_loss:.4f}  "
              f"IoU={metrics['iou']:.3f}  Dice={metrics['dice']:.3f}")

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            best_epoch    = epoch
            save_checkpoint(model, MODEL_OUT, extra_metadata={
                "best_epoch": epoch,
                "best_val_loss": round(best_val_loss, 4),
            })

    print(f"\nBest checkpoint: epoch {best_epoch}, val_loss={best_val_loss:.4f}")

    # ── Save metrics with explicit SYNTHETIC label ──
    best_metrics = next(h for h in history if h["epoch"] == best_epoch)
    metrics_doc = {
        "NOTICE": (
            "These metrics were computed on SYNTHETIC SAR data only. "
            "They are NOT real-world Sentinel-1 validation results. "
            "Do NOT report these as real-world accuracy. "
            "Real-world performance requires evaluation on a labeled Sentinel-1 dataset."
        ),
        "data_source": "SYNTHETIC_SAR_v1",
        "architecture": "VanillaUNet",
        "preprocessing_version": PREPROCESSING_VERSION,
        "synthetic_validation": {
            "iou":              best_metrics["iou"],
            "dice":             best_metrics["dice"],
            "precision":        best_metrics["precision"],
            "recall":           best_metrics["recall"],
            "f1":               best_metrics["f1"],
            "best_epoch":       best_epoch,
            "optimal_threshold": 0.45,
        },
        "real_validation": {
            "NOTICE": "Real Sentinel-1 evaluation has NOT been performed.",
            "iou":       None,
            "dice":      None,
            "precision": None,
            "recall":    None,
        },
        "training_history": history,
    }
    with open(METRICS_OUT, "w") as f:
        json.dump(metrics_doc, f, indent=2)
    print(f"Metrics saved: {METRICS_OUT}")


if __name__ == "__main__":
    train()
