-- Migration 002: Persistent Incidents Table
CREATE TABLE IF NOT EXISTS incidents (
    id TEXT PRIMARY KEY,
    mmsi TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    state TEXT NOT NULL DEFAULT 'AIS_NORMAL',
    anomaly_detected BOOLEAN DEFAULT FALSE,
    anomaly_score DOUBLE PRECISION,
    sar_status TEXT DEFAULT 'DEFERRED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE incidents ADD COLUMN IF NOT EXISTS timestamp TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS latitude DOUBLE PRECISION;
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS longitude DOUBLE PRECISION;
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS state TEXT DEFAULT 'AIS_NORMAL';
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS anomaly_detected BOOLEAN DEFAULT FALSE;
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS anomaly_score DOUBLE PRECISION;
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS sar_status TEXT DEFAULT 'DEFERRED';
ALTER TABLE incidents ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

CREATE INDEX IF NOT EXISTS idx_incidents_mmsi ON incidents(mmsi);
CREATE INDEX IF NOT EXISTS idx_incidents_created_at ON incidents(created_at DESC);